### ISSUE TITLE
Assertation failed

### ISSUE THREAD

**Issue by ivanstepanovftw** [oliora/bitmask#7]
Should this code ever work?
```c++
#include "iostream"
#include "bitmask.hpp"

enum class region_mode_t : uint8_t
{
    none = 0,
    executable = 1u<<0u,
    writable   = 1u<<1u,
    readable   = 1u<<2u,
    shared     = 1u<<3u,
    max = executable|writable|readable|shared
};
BITMASK_DEFINE_MAX_ELEMENT(region_mode_t, max)

int main(int argc, char *argv[]) {
    using namespace std;
    
    bitmask::bitmask<region_mode_t> flags;

    flags = region_mode_t::none;
    flags = region_mode_t::shared;
    flags = region_mode_t::readable;
    flags = region_mode_t::executable;
    flags = region_mode_t::writable; // a.out: bitmask.hpp:135: bitmask::bitmask_detail::checked_value(T, T) [with T = unsigned char]::<lambda()>: Assertion `!"(value & ~mask) == 0"' failed.

    cout<<"flags:w is "<<((flags & region_mode_t::writable) != 0)<<endl;
}
```

oliora/bitmask:master
gcc version 8.2.1 20181127 (GCC)
5.1.0-1-MANJARO

**Comment by ivanstepanovftw** [comment]
It is worked before... I don't get it.

**Comment by ivanstepanovftw** [comment]
Fails only for `writable` (1<<1). Tried to change uint8_t to uint16_t, tried to add `max = 0u|executable|writable|readable|shared` (clang reports `Clang-Tidy: Use of a signed integer operand with a binary bitwise operator` for `executable`). Workaround:
```c++
enum class region_mode_t : uint8_t
{
    none = 0,
    executable = 1u<<0u,
    idk        = 1u<<1u,
    writable   = 1u<<2u,
    readable   = 1u<<3u,
    shared     = 1u<<4u,
    max = executable|writable|readable|shared|idk
};
```

**Comment by ivanstepanovftw** [comment]
My fault. Final code:
```c++
enum class region_mode_t : uint8_t
{
    none = 0,
    executable = 1u<<0u,
    writable   = 1u<<1u,
    readable   = 1u<<2u,
    shared     = 1u<<3u,
    max = executable|writable|readable|shared
};
BITMASK_DEFINE_MAX_ELEMENT(region_mode_t, shared)
```
Still cant believe that it is worked before for a several months.

**Comment by oliora** [comment]
Updated:
This is correct now but the definition of `max` is really confusing because it's not a max element but a mask of all possible bits.
Actually you can use `bitmask::mask()` to get the same value as `max` you’ve defined.

FYI there is also another way of definition of the same:
`BITMASK_DEFINE_VALUE_MASK(region_mode_t, region_mode_t::max)` but I can not recommend it for enum with contiguous distinct values.

**Comment by oliora** [comment]
Closing as there is no issue
