### ISSUE TITLE
Can not compile sample code

### ISSUE THREAD

**Issue by acsvln** [oliora/bitmask#8]
I have copy pasted this code sample:
```
enum class open_mode
{
  binary = 0x01,
  app = 0x02,
  in = 0x04,
  out = 0x08,
  trunc = 0x10,
  ate = 0x20,

  // 2. Define max bitmask value
  _bitmask_max_element = ate
};

// 3. Enable bitmask features for the enum
BITMASK_DEFINE(open_mode)
```
And got some compiler errors: C2955, C3083, C2039.
I am using MSVC from Visual Studio 2017.
I have no idea why it breaks compilation with assertion in function **checked_value**.

**Comment by oliora** [comment]
Hi! Can you post the error you get from the compiler?

**Comment by oliora** [comment]
I think I've fixed the issue. Please close the issue if it's fixed or provide the compiler error that you get.

**Comment by acsvln** [comment]
Thanks a lot!
