### ISSUE TITLE
Readme typo?

### ISSUE THREAD

**Issue by greg7mdp** [oliora/bitmask#9]
Is this right?
![image](https://user-images.githubusercontent.com/1496907/92260484-f7a4ab00-eea5-11ea-892b-7c356ecac9f7.png)

**Comment by oliora** [comment]
Haha, surely a typo. Good catch!

**Comment by oliora** [comment]
Fixed in https://github.com/oliora/bitmask/commit/0454f32733d4fc910ac0c3c85e61b45b9ae7eee9
